# Generated by Django 3.2.18 on 2023-05-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_recommendedvalues_fish_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquarium',
            name='aquarium_id',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
