# Generated by Django 3.2.18 on 2023-05-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_aquarium_aquarium_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aquarium',
            name='general_system_state',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='aquarium',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='aquarium',
            name='length',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='aquarium',
            name='volume',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='aquarium',
            name='water_level',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='aquarium',
            name='width',
            field=models.FloatField(default=0),
        ),
    ]
