# Generated by Django 3.2.18 on 2023-05-15 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20230515_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aquarium',
            name='fish_id',
        ),
        migrations.RemoveField(
            model_name='aquarium',
            name='water_type',
        ),
    ]
