# Generated by Django 3.2.18 on 2023-05-15 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20230515_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aquarium',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile'),
        ),
    ]
