# Generated by Django 3.2.18 on 2023-06-13 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20230613_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquarium',
            name='fish_id',
            field=models.ManyToManyField(to='user.Fish'),
        ),
        migrations.AddField(
            model_name='aquarium',
            name='water_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.watertype'),
        ),
    ]
