# Generated by Django 3.2.18 on 2023-06-13 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20230613_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aquarium',
            name='fish_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.fish'),
        ),
    ]
