# Generated by Django 3.2.18 on 2023-06-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20230613_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aquarium',
            name='fish_id',
            field=models.ManyToManyField(null=True, to='user.Fish'),
        ),
    ]
