# Generated by Django 3.2.18 on 2023-06-13 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_aquarium_fish_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aquarium',
            name='fish_id',
        ),
        migrations.AddField(
            model_name='aquarium',
            name='fish_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.fish'),
        ),
        migrations.RemoveField(
            model_name='fish',
            name='food_id',
        ),
        migrations.AddField(
            model_name='fish',
            name='food_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.food'),
        ),
    ]
