# Generated by Django 3.2.18 on 2023-06-13 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20230613_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='food_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.food'),
        ),
    ]
