# Generated by Django 3.2.18 on 2023-06-13 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_fish_food_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='fish_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.watertype'),
        ),
    ]
