# Generated by Django 3.2.18 on 2023-06-13 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_fish_fish_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aquarium',
            name='fish_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.fish'),
        ),
    ]
