# Generated by Django 3.2.18 on 2023-06-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_alter_aquarium_fish_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aquarium',
            name='fish_id',
        ),
        migrations.AddField(
            model_name='aquarium',
            name='fish_id',
            field=models.ManyToManyField(to='user.Fish'),
        ),
    ]
