# Generated by Django 3.2.18 on 2023-06-14 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_auto_20230614_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='aquarium_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='user.aquarium'),
        ),
    ]
