# Generated by Django 3.2.18 on 2023-06-14 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_auto_20230614_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aquarium',
            name='sensors',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.sensor'),
        ),
    ]
