# Generated by Django 3.2.18 on 2023-06-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_auto_20230614_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aquarium',
            name='sensors',
            field=models.ManyToManyField(default=None, to='user.Sensor'),
        ),
    ]
