# Generated by Django 3.2.18 on 2023-06-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_auto_20230614_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='current_time',
            field=models.DateTimeField(blank=True, default='00:00'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='current_value',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
