# Generated by Django 3.2.18 on 2023-06-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_auto_20230614_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='current_time',
            field=models.DateTimeField(blank=True, default='1900-01-01 00:00'),
        ),
    ]
