# Generated by Django 3.2.18 on 2023-06-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_alter_sensor_current_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aquarium',
            name='water_level',
            field=models.FloatField(default=86.0),
        ),
    ]
