# Generated by Django 3.2.18 on 2023-06-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_alter_aquarium_water_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(choices=[('TEMPERATURE', 'Temperature'), ('PH', 'PH'), ('OXYGEN', 'Oxygen'), ('TURBIDITY', 'Turbidity'), ('NITRATE', 'Nitrate'), ('DURITY', 'Durity'), ('AMMONIUM', 'Ammonium')], default='Temperature', max_length=11),
        ),
    ]
