# Generated by Django 3.2.18 on 2023-06-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_sensor_sensor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='ideal_value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(choices=[('TEMPERATURE', 'Temperature'), ('PH', 'PH'), ('OXYGEN', 'Oxygen'), ('TURBIDITY', 'Turbidity'), ('NITRATE', 'Nitrate'), ('DURITY', 'Durity'), ('AMMONIUM', 'Ammonium')], default='TEMPERATURE', max_length=11),
        ),
    ]
