# Generated by Django 3.2.18 on 2023-06-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_auto_20230614_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_value', models.FloatField(blank=True, default=0.0)),
                ('sensor_time', models.DateTimeField(blank=True, default='1900-01-01 00:00')),
                ('sensor_id', models.ManyToManyField(to='user.Sensor')),
            ],
        ),
    ]
