# Generated by Django 3.2.18 on 2023-06-14 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_sensorhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorhistory',
            name='aquarium_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='user.aquarium'),
        ),
    ]
