# Generated by Django 3.2.18 on 2023-06-14 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_sensorhistory_aquarium_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorhistory',
            name='sensor_id',
        ),
        migrations.AddField(
            model_name='sensorhistory',
            name='sensor_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='user.sensor'),
        ),
    ]
