# Generated by Django 3.2.18 on 2023-06-14 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0041_auto_20230614_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorhistory',
            name='aquarium_id',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.RemoveField(
            model_name='sensorhistory',
            name='sensor_id',
        ),
        migrations.AddField(
            model_name='sensorhistory',
            name='sensor_id',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='HistoricalSensorHistory',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('aquarium_id', models.CharField(default=None, max_length=20)),
                ('sensor_id', models.IntegerField(default=0)),
                ('sensor_value', models.FloatField(blank=True, default=0.0)),
                ('sensor_time', models.DateTimeField(blank=True, default='1900-01-01 00:00')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical sensor history',
                'verbose_name_plural': 'historical sensor historys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
