# Generated by Django 3.2.18 on 2023-06-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0043_auto_20230615_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsensorhistory',
            name='aquarium_id',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='historicalsensorhistory',
            name='sensor_id',
            field=models.IntegerField(default=0),
        ),
    ]
