# Generated by Django 3.2.18 on 2023-06-14 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0044_auto_20230615_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsensorhistory',
            name='time_period',
            field=models.CharField(choices=[('DAY', 'Day'), ('WEEK', 'Week'), ('MONTH', 'Month'), ('YEAR', 'Year')], default='Day', max_length=5),
        ),
        migrations.AddField(
            model_name='sensorhistory',
            name='time_period',
            field=models.CharField(choices=[('DAY', 'Day'), ('WEEK', 'Week'), ('MONTH', 'Month'), ('YEAR', 'Year')], default='Day', max_length=5),
        ),
    ]
