# Generated by Django 3.2.18 on 2023-06-14 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0045_auto_20230615_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsensorhistory',
            name='nr_records',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='sensorhistory',
            name='nr_records',
            field=models.IntegerField(default=7),
        ),
    ]
