# Generated by Django 3.2.18 on 2023-06-14 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0046_auto_20230615_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsensorhistory',
            name='time_period',
            field=models.CharField(choices=[('DAY', 'Day'), ('WEEK', 'Week'), ('MONTH', 'Month'), ('YEAR', 'Year')], default='DAY', max_length=5),
        ),
        migrations.AlterField(
            model_name='sensorhistory',
            name='time_period',
            field=models.CharField(choices=[('DAY', 'Day'), ('WEEK', 'Week'), ('MONTH', 'Month'), ('YEAR', 'Year')], default='DAY', max_length=5),
        ),
    ]
